services:
 backend:
  container_name: backend
  networks:
   - transcendence 
  build: backend/ 
  develop:
   watch:
     - action: sync
       path: backend
       target: /app
       ignore:
        - node_modules/
        - Dockerfile
        - tsconfig.json
     - action: rebuild
       path: backend/package.json
  restart: always
  volumes:
   - ./backend/db:/app/db
 frontend:
  depends_on:
   - backend 
  container_name: frontend
  networks:
   - transcendence 
  build: frontend/ 
  develop:
   watch:
     - action: rebuild
       path: frontend
       target: /usr/share/nginx/html
       ignore:
        - node_modules/
        - Dockerfile
     - action: rebuild
       path: frontend/package.json
  restart: always
  ports: 
    - 8080:443

networks:
 transcendence:
  driver: bridge
