services:
  backend:
    container_name: backend
    networks:
      - transcendence
    build: backend/
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./backend/app/db:/app/db
      # Volume pour le développement (remplace develop)
      - ./backend:/app
      - /app/node_modules

  frontend:
    depends_on:
      - backend
    container_name: frontend
    networks:
      - transcendence
    build: frontend/
    restart: always
    ports:
      - 8080:443
    volumes:
      # Volume pour le développement (remplace develop)
      - ./frontend:/usr/share/nginx/html
      - /usr/share/nginx/html/node_modules

networks:
  transcendence:
    driver: bridge
