services:
  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - transcendence
    env_file: .env
    develop:
      watch:
        - action: sync
          path: backend
          target: /app
          ignore:
            - node_modules/
            - Dockerfile
            - tsconfig.json
        - action: rebuild
          path: backend/package.json
    volumes:
      - ./backend/app/db:/app/db  # SQLite persistante

  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:443"
    networks:
      - transcendence
    develop:
      watch:
        - action: rebuild
          path: frontend
          target: /usr/share/nginx/html
          ignore:
            - node_modules/
            - Dockerfile
        - action: rebuild
          path: frontend/package.json

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - transcendence
    depends_on:
      - backend
      - cadvisor

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/provisioning/alerting:/etc/grafana/provisioning/alerting
      - ./monitoring/grafana/dashboard:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    env_file: .env
    environment:
      - GF_LOG_LEVEL=warn
    networks:
      - transcendence
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    networks:
      - transcendence
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:

networks:
  transcendence:
    driver: bridge
