services:
 backend:
  depends_on: 
   - reverse_proxy
  container_name: backend
  build: srcs/backend/ 
  develop:
   watch:
     - action: sync
       path: srcs/backend/
       target: app/
       ignore:
        - node_modules/
     - action: rebuild
       path: srcs/backend/package.json
  restart: always
  volumes:
   - ./srcs/backend/db:/app/db
  ports: 
   - 8080:8080
 frontend:
  depends_on:
   - backend 
  container_name: frontend
  build: srcs/frontend/ 
  develop:
   watch:
     - action: sync
       path: srcs/frontend
       target: app/
       ignore:
        - node_modules/
     - action: rebuild
       path: srcs/frontend/package.json
  restart: always
  ports: 
   - 3000:3000
 reverse_proxy:
  container_name: reverse_proxy
  build: srcs/reverse_proxy
  ports: 
      - 8443:443
  restart: always
