services:
 backend:
    #depends_on: #"?" #database
  container_name: backend
  networks:
    - transcendence
  build: srcs/backend/ 
  develop:
   watch:
     - action: sync
       path: srcs/backend/
       target: app/
       ignore:
        - node_modules/
     - action: rebuild
       path: srcs/backend/package.json
  restart: always
  volumes:
      - sqlite:/app/db
  ports: 
   - 8080:8080
 frontend:
    #depends_on: "?" #backend 
  container_name: frontend
  networks:
    - transcendence
  build: srcs/frontend/ 
  develop:
   watch:
     - action: sync
       path: srcs/frontend
       target: app/
       ignore:
        - node_modules/
     - action: rebuild
       path: srcs/frontend/package.json
  restart: always
  ports: 
   - 3000:3000

networks:
 transcendence:
  driver: bridge

volumes:
 sqlite:
  driver: local
  driver_opts:
    type: none
    o: bind
    device: ./srcs/backend/db

