apiVersion: 1
groups:
  - orgId: 1
    name: Backend Alerts
    folder: Transcendence
    interval: 1m
    rules:
      - uid: backend-down
        title: BackendDown (Grafana)
        condition: A
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: prometheus
            model:
              expr: avg_over_time(up{job="backend"}[5m]) < 1
              instant: false
              interval: ""
              legendFormat: ""
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 2m
        annotations: { severity: critical }
        labels: { service: backend }
      - uid: eventloop-lag
        title: EventLoopLagHigh (Grafana)
        condition: A
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: prometheus
            model:
              expr: max_over_time(ft_nodejs_eventloop_lag_seconds[5m]) > 0.2
              instant: false
              interval: ""
              legendFormat: ""
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations: { severity: warning }
        labels: { service: backend }
